# Generated by Django 5.2.1 on 2025-06-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Porcentaje de descuento (ej. 0.10 para 10%). Máximo 1.00 (100%).', max_digits=5),
        ),
    ]
