# Generated by Django 5.2.1 on 2025-06-27 15:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_producto_descuento'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descuento',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Porcentaje de descuento (ej. 0.10 para 10%). Máximo 1.00 (100%).', max_digits=5),
        ),
    ]
