# Generated by Django 5.2.1 on 2025-06-25 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categorias', '0001_initial'),
        ('empresas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='empresas.empresa', verbose_name='Empresa'),
        ),
        migrations.AlterUniqueTogether(
            name='categoria',
            unique_together={('nombre', 'empresa')},
        ),
    ]
